name: kaycore_auth
description: An authentication SDK package for Kayko
version: 1.0.0
homepage: https://kayko.rw

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5

dev_dependencies:
  coverage: ^1.1.0
  meta: ^1.8.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
  lints: ^2.0.0
  http_mock:
    git:
      url: https://github.com/kaykorw/http_mock
      ref: main
